steps:
  - command: "./rebar3 as test compile"
    key: "build"
  - command: "./rebar3 eunit"
    depends_on: "build"
    agents:
      queue: "erlang"
  - command: "./rebar3 ct"
    depends_on: "build"
    agents:
      queue: "erlang"
  - command: "./rebar3 xref"
    depends_on: "build"
    agents:
      queue: "erlang"
  - command: "./rebar3 dialyzer"
    depends_on: "build"
    agents:
      queue: "erlang"
