steps:
  - command: "./rebar3 eunit"
    depends_on: ~
    allow_failure: true
    agents:
      queue: "erlang"
  - command: "./rebar3 ct"
    depends_on: ~
    allow_failure: true
    agents:
      queue: "erlang"
  - command: "./rebar3 xref"
    depends_on: ~
    allow_failure: true
    agents:
      queue: "erlang"
  - command: "./rebar3 dialyzer"
    depends_on: ~
    allow_failure: true
    agents:
      queue: "erlang"
